package com.mibs.mars.test;
import org.junit.Test;

import com.mibs.mars.Library;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'admin2' at '30.01.18 11:17' with Gradle 2.11
 *
 * @author admin2, @date 30.01.18 11:17
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
