package com.mibs.mars;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'admin2' at '30.01.18 11:17' with Gradle 2.11
 *
 * @author admin2, @date 30.01.18 11:17
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
